config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"
  scope module: :public do
    get 'search' => 'books#search'
     delete "/books/:id/destroy" => "books#destroy", as: "destroy"
     delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
   resources :books, only: [:show, :new, :index, :edit, :create]
     get "my_page" => "users#show", as: "my_page"
     get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
     patch "/users/withdraw" => "users#withdraw", as: "withdraw"
     patch "book/:id" => "books#update", as: "update_book"
   resources :users, only: [:show, :edit, :update] do
      collection do
      get 'search'
    end
  end
     delete "/assessments/:id/destroy" => "assessments#destroy", as: "destroy_assessment"
   resources :assessments, only: [:new, :update, :create, :show, :edit]
   resources :posts, only: [:new, :index, :create, :edit, :update]
     delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'

  end

  namespace :admin do
    root to: "/homes#top"
    resources :users, only: [:show, :update, :index, :edit, :create]
    resources :books, only: [:show, :new, :index, :edit, :update, :create]
    delete "/books/:id/destroy" => "books#destroy", as: "destroy"
    delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    has_many :assessments, dependent: :destroy
    has_many :posts, dependent: :destroy
    belongs_to :user

    has_one_attached :image

     validates :title, presence: true

    def self.search(keyword)
     where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
    end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

  def index
    if params[:keyword].present?
     @books = Book.search(params[:keyword])
    else
     @books = Book.page(params[:page])
    end
     @books = @books.page(params[:page])
  end

  def new
     @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save!
    pp @book
    redirect_to admin_books_path
  end

  def edit
  end

  def show
    @book = Book.find(params[:id])
    @book_assessments = Assessment.where(book_id: @book.id)
  end

  def destroy
   @book = Book.find(params[:id])
   @book.destroy
   redirect_to admin_books_path
  end

  def update
    @book = Book.find{params[:id]}
    @book.update(user_params)
    redirect_to admin_books_path
  end

   private

  def book_params
    params.require(:book).permit(:image, :book_image, :title, :body, :author, :comment)
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/index.html.erb
 <div class = "top_admin_layout">
  <div class = "admin_book_sarch_title" >
   本を検索する
  </div>
  <div class = "admin_book_layout">
   <div class = "admin_book_sarch" >
    <%= form_with method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" %>
    <% end %>
   </div><br>


    <h4 class = "admin_book_index" >
     本一覧
    </h4>
     <% if @books.present? %>
      <table class="table">
        <tr>
         <th class = "admin_book_index" scope="col">book_image</th>
         <th class = "admin_book_index" scope="col">id</th>
         <th class = "admin_book_index" scope="col">title</th>
         <th class = "admin_book_index" scope="col">author</th>
        </tr>
         <% @books.each do |book| %>
          <tr>
            <td>
              <% if book.image.attached? %>
               <%= image_tag book.image, size: "150x150" %>
              <% else %>
               <%= image_tag 'book', size: "150x150" %>
              <% end %>
            </td>
            <td class = "admin_book_index_contents">
             <%= link_to admin_book_path(book.id) do %>
              <%= book.id %>
             <% end %>
            </td>
            <td class = "admin_book_index_contents">
             <%= book.title %>
            </td>
            <td class = "admin_book_index_contents">
             <%= book.author %>
            </td>
          </tr>
          <% end %>
          <% else %>
           <p>検索結果はありません</p>
          <% end %>
     </table>
      <div class = "admin_book_page">
       <%= paginate @books %>
      </div>
 </div>
</div>

app/views/admin/books/new.html.erb
<div class = "admin_book_new">
 <%= form_with model: @book, url:admin_books_path, local:true do |f| %>
    <h4>book_image</h4>
     <%= f.file_field :image, accept: "image/*" %>
    <h4>title</h4>
     <%= f.text_field :title %>
    <h4>author</h4>
     <%= f.text_field :author %>
   <h4></h4>
     <%= f.submit '登録' %>
 <% end %>
</div>

app/views/admin/books/show.html.erb
<div class = "top_book_show">
 <table class="table">
  <tr>
   <th class = book_show_content scope="col"></th>
   <th class = book_show_content scope="col">ID</th>
   <th class = book_show_content scope="col">本のタイトル</th>
   <th class = book_show_content scope="col">本の著者</th>
   <th class = book_show_content scope="col">本のコメント</th>
  </tr>
   <tr>
    <td class = book_show_content_sub scope="col">
     <% if @book.image.attached? %>
      <%= image_tag @book.image, size: "250x250" %>
     <% else %>
      <%= image_tag 'book', size: "250x250" %>
     <% end %>
    </td>
    <td class = book_show_content_sub scope="col"><%= @book.id %></td>
    <td class = book_show_content_sub scope="col"><%= @book.title %></td>
    <td class = book_show_content_sub scope="col"><%= @book.author %></td>
    <td class = book_show_content_comment scope="col">
     <% @book_assessments.each do |assessment| %>
      <%= assessment.comment %>
      <%= link_to "削除", destroy_assessment_path(assessment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %><br>
     <% end %>
    </td>
 </table>
</div>
<%= link_to "一覧画面へ", admin_books_path %><br>
<%= link_to "登録を削除する", destroy_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>