config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"
  scope module: :public do
    get 'search' => 'books#search'
     delete "/books/:id/destroy" => "books#destroy", as: "destroy"
     delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
   resources :books, only: [:show, :new, :index, :edit, :create]
     get "my_page" => "users#show", as: "my_page"
     get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
     patch "/users/withdraw" => "users#withdraw", as: "withdraw"
     patch "book/:id" => "books#update", as: "update_book"
   resources :users, only: [:show, :edit, :update] do
      collection do
      get 'search'
    end
  end
     delete "/assessments/:id/destroy" => "assessments#destroy", as: "destroy_assessment"
   resources :assessments, only: [:new, :update, :create, :show, :edit]
   resources :posts, only: [:new, :index, :create, :edit, :update]
     delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'

  end

  namespace :admin do
    root to: "/homes#top"
    resources :users, only: [:show, :update, :index, :edit, :create]
    resources :books, only: [:show, :new, :index, :edit, :update, :create]
    delete "/books/:id/destroy" => "books#destroy", as: "destroy"
    delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assessments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :books, dependent: :destroy

  has_one_attached :image

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @user = User.all
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

 private
  def user_params
    params.require(:user).permit(:name, :sex, :age, :birthdate, :email, :image, :is_active, :boolean)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h2 class = "admin_user_edit_title" >
  会員編集画面
</h2>
 <div class= "top_admin_user_edit">
     <%= form_with model: @user, url:admin_user_path(@user.id), method: :patch, local: true do |f| %>
       <div class = "admin_user_edit_content">
        <% if @user.image.attached? %>
         <%= image_tag @user.image, size: "100x100" %>
        <% else %>
          <%= image_tag "no_image.jpg" %>
        <% end %>
        <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %>
       <div class = "admin_user_edit_content">name</div>
       <div>
        <%= f.text_field :name %>
       </div>
       <div class = "admin_user_edit_content">sex</div>
        <%= f.text_field :sex %>
       <div class = "admin_user_edit_content">birthdate</div>
        <%= f.text_field :birthdate %>
       <div class = "admin_user_edit_content">age</div>
        <%= f.text_field :age %>
       <div class = "admin_user_edit_content">mail</div>
        <%= f.text_field :email %>
       <div class = "admin_user_edit_content">status</div>
        <%= f.text_field :is_active %>
        <%= f.submit '変更を保存する' %>
     <% end %>
 </div>

app/views/admin/users/index.html.erb
<div class = "top_admin_user">
 <h4 class = "admin_user_index">
  会員一覧
 </h4>
  <table class="table">
   <tr>
      <th class = "admin_user_content" scope="col">user</th>
      <th class = "admin_user_content" scope="col">user_ID</th>
      <th class = "admin_user_content" scope="col">name</th>
      <th class = "admin_user_content" scope="col">sex</th>
      <th class = "admin_user_content" scope="col">birthdate</th>
      <th class = "admin_user_content" scope="col">age</th>
      <th class = "admin_user_content" scope="col">mail</th>
      <th class = "admin_user_content" scope="col">status</th>
      <th></th>
   </tr>
     <% @users.each do |user| %>
      <tr>
       <td> <% if user.image.attached? %>
        <%= image_tag user.image, size: "100x100" %>
         <% else %>
        <%= image_tag "no_image.jpg" %>
         <% end %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.id %>
       </td>
       <td class = "admin_user_index_content">
        <%= link_to admin_user_path(user.id) do %>
         <%= user.name %>
        <% end %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.sex %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.birthdate %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.age %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.email %>
       </td>
       <td class = "admin_user_index_content">
        <%= user.is_active %>
       </td>
       <td class = "admin_user_index_content">
        <%= link_to "詳細画面へ",admin_user_path(user.id) %>
       </td>
       <% end %>
      </tr>
  </table>
  <div class = "admin_page">
   <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class = "top_admin_user_show">
 <h2 class = admin_user_show_title >
  会員詳細画面
 </h2>
 <table class="table">
  <tr>
    <th class = admin_user_show_content scope="col">user</th>
    <th class = admin_user_show_content scope="col">user_id</th>
    <th class = admin_user_show_content scope="col">name</th>
    <th class = admin_user_show_content scope="col">sex</th>
    <th class = admin_user_show_content scope="col">birthdate</th>
    <th class = admin_user_show_content scope="col">age</th>
    <th class = admin_user_show_content scope="col">mail</th>
    <th class = admin_user_show_content scope="col">status</th>
  </tr>
   <tr>
    <td class = "admin_user_show_content" >
     <% if @user.image.attached? %>
      <%= image_tag @user.image, size: "100x100" %>
       <% else %>
      <%= image_tag "no_image.jpg" %>
       <% end %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.id %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.name %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.sex %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.birthdate %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.age %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.email %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= @user.is_active %>
    </td>
    <td class = "admin_user_show_contents" >
     <%= link_to "編集する",edit_admin_user_path(@user.id) %>
    </td>
   </tr>
 </table>
</div>