config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"
  scope module: :public do
    get 'search' => 'books#search'
     delete "/books/:id/destroy" => "books#destroy", as: "destroy"
     delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
   resources :books, only: [:show, :new, :index, :edit, :create]
     get "my_page" => "users#show", as: "my_page"
     get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
     patch "/users/withdraw" => "users#withdraw", as: "withdraw"
     patch "book/:id" => "books#update", as: "update_book"
   resources :users, only: [:show, :edit, :update] do
      collection do
      get 'search'
    end
  end
     delete "/assessments/:id/destroy" => "assessments#destroy", as: "destroy_assessment"
   resources :assessments, only: [:new, :update, :create, :show, :edit]
   resources :posts, only: [:new, :index, :create, :edit, :update]
     delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'

  end

  namespace :admin do
    root to: "/homes#top"
    resources :users, only: [:show, :update, :index, :edit, :create]
    resources :books, only: [:show, :new, :index, :edit, :update, :create]
    delete "/books/:id/destroy" => "books#destroy", as: "destroy"
    delete "/books/destroy_all" => "books#destroy_all", as: "destroy_all"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecommendedBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  <body class="d-flex flex-column vh-100">
   <%= notice %>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span><i class="fas fa-book-reader"></i>RecommendedBooks</span></a>
           <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                 ようこそ、<%= current_user.name %>さん！
                  <li class="nav-item">
                   <%= link_to my_page_path, class: 'nav-link text-dark' do %>
                     <i class="fas fa-home"></i> マイページ
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to books_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-search"></i> 本の検索（一覧）
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to posts_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-book-open"></i> 読みたい本一覧
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to unsubscribe_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-running"></i> 退会する
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                   <% end %>
                  </li>

                 <% elsif admin_signed_in? %>
                  <li class="nav-item">
                   <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-user"></i>会員一覧
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to admin_books_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-user"></i>本の一覧
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                   <% end %>
                  </li>

                 <% else %>
                  <li class="nav-item">
                   <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-link"></i>About
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to books_path, class: 'nav-link text-dark' do %>
                     <i class="fas fa-search"></i> 本の検索（一覧）
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-user-plus"></i> Sign up
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                   <% end %>
                  </li>
                 <% end %>
             </ul>
            </div>
           </div>
          </nav>
         </header>
        <main class="mb-auto">
         <%= yield %>
        </main>
         <footer class="bg-dark text-white pt-5 pb-4">
            <div class="container">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <i class="fas fa-book-reader"></i><span>recommended_books</span>
                </div>
                <div class="col-md-8">
                  <h6 class="text-white mt-2 mb-3">画像参考サイト https://www.hanmoto.com/</h6>
                  <ul class="p-0 list-unstyled">
                    <li>
                     <a href="" title="About" class="text-white-50">
                        <div class = footerr>
                         <%= link_to about_path, class: 'nav-link text-light' do %>
                          recommended_booksとは？
                         <% end %>
                        </div>
                     </a>
                    </li>
                    <li>
                      <a href="" title="License informations" class="text-white-50"></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </footer>
        </body>
      </html>
     </body>
   </html>